os: osx
language: objective-c
xcode_workspace: Project.xcworkspace # path to your xcodeproj folder
osx_image: xcode8.3

branches:
  only:
    - master
    
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  
podfile: ./Podfile

script:
  - set -o pipefail
  - pod install
  - xcodebuild -workspace WingIt.xcworkspace -scheme WingIt -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
