os: osx
language: objective-c
xcode_workspace: Project.xcworkspace # path to your xcodeproj folder
osx_image: xcode8.3

branches:
  only:
    - master
    - travis
    
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  
podfile: ./Podfile
pod install

script:
  - set -o pipefail
  - xcodebuild -workspace Project.xcworkspace -scheme TravisBuild -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
